config/routes.rb
Rails.application.routes.draw do
  root 'dashboards#index'
  resources :posts
  get 'dashboards/index', as: :dashboards
  get 'logout', to: "logins#logout"
  resources :logins, only: [:new, :create]
  resources :registrations, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :password, presence: true
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_user

  def set_user
    @user = User.find_by(id: session[:user_id])
  end
  def require_login
    @user = User.find_by(id: session[:user_id])
    redirect_to new_login_path unless @user
  end
  def authenticated(user)
    @user = user
  end
  def logged_out
    @user = nil
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
    @user = User.find_by(id: session[:user_id])
    @posts = Post.all
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to dashboards_path if user
    @user = User.new
  end

  def logout
    reset_session
    logged_out
    redirect_to root_path, notice: "You are now logged out."
  end

  def create
    @user = User.find_by(login_params)

    if @user
      session[:user_id] = @user.id
      redirect_to dashboards_path
    else
      flash[:alert] = "Could not log you in. Please check your email and password."
      render :new, status: :unprocessable_entity
    end
  end

  private
  def login_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :require_login, only: %i[ new create ]
  before_action :require_authorization, only: %i[ edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = @user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    title = @post.title
    @post.destroy
    redirect_to dashboards_path, notice: "Successfully destroyed '#{title}'"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def require_authorization
    post = Post.find(params[:id])
    redirect_to dashboards_path, notice: "Action not authorized." if @user.nil? || post.user_id != @user.id
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to dashboards_path if user
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_login_path
    else
      flash[:alert] = "Could not create account: email and password required."
      render :new, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper
  def authenticated?
    !(@user.nil? || @user.id.nil?)
  end
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }
    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = ::Redcarpet::Render::HTML.new(options)
    markdown = ::Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/dashboards/index.html.erb
<div class="text-xl mb-8">Latest Posts</div>
<% @posts.each do |post| %>
  <div class="h-12 m-2 flex">
    <%= link_to post.title, post_path(post) %>,&nbsp;
    <span class="italic">
      <%= post.user.name %>
    </span>
    <% if post.user == @user %>
      <div class="flex px-2">
      <span class="flex text-xs items-center justify-center h-8 w-fit mr-2 border-2 border-blue-500 px-2 bg-blue-50 rounded-md">
        <%= link_to "edit", edit_post_path(post), class: "hover:text-black hover:font-normal" %>
      </span>
      <span class="text-xs">
        <%= button_to "delete", post, method: :delete, class: "px-2 h-8 border-2 border-blue-500 bg-blue-50 rounded-md" %>
      </span>
      </div>
    <% end %>
  </div>
<% end %>
<%#= render @posts %>

app/views/layouts/_menu.html.erb
<div>
  <% if @user.nil? || @user.id.nil? %>
    <div><%= link_to "Home", root_path %></div>
    <div><%= link_to "Login", new_login_path %></div>
    <div><%= link_to "Register", new_registration_path %></div>
  <% else %>
    <div><%= link_to "Dashboard", dashboards_path %></div>
    <div><%= link_to "Write", new_post_path %></div>
    <div><%= link_to "Logout", logout_path %></div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authentication</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="container mx-auto mt-4 px-4 bg-blue-400 font-mono">
<%# flash styling thanks to: https://stackoverflow.com/questions/73129428/flash-messages-with-stimulus-js-and-animate-css %>
<% flash.each do |message_type, message| %>
  <div data-controller="flash" class="absolute left-1/2 transform -translate-x-1/2">
    <div class="mt-5 mb-15 sm:mx-auto sm:w-full sm:max-w-md px-2">
      <div class="flex center-justify rounded-md bg-blue-50 p-4 text-sm font-medium">
        <%= message %>
      </div>
    </div>
  </div>
<% end %>
<div class="bg-white p-4 grid grid-cols-2 items-bottom">
  <div class="flex">
    <div class="mt-auto p-2">
      <%= image_tag ("dalle-typewriter-sm.jpg") %>
    </div>
    <div class="mt-auto p-4 text-2xl">
      Blog on Rails
    </div>
  </div>
  <div class="text-right">
    <%= "Logged in as #{@user.name}" if authenticated? %>
  </div>
</div>
<div class="grid grid-cols-5 gap-3">
  <div class="bg-gray-200 p-4">
    <%= render "layouts/menu" %>
  </div>
  <div class="bg-white col-span-4 p-4">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/new.html.erb
<h1>Welcome Back! Log In</h1>
<%= form_with model: @user, url: logins_path do |form| %>
  <div class="my-5">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div class="my-5">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div class="my-5 w-fit px-2 border-2 border-blue-500 p-1 bg-blue-50 rounded-md">
    <%= form.submit "Log In" %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>


  <div class="my-5">
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, :cols => "60" %>
  </div>
  <span class="border-2 border-blue-500 p-1 bg-blue-50 rounded-md">
    <%= form.submit "Save" %>
  </span>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= markdown(post.body) %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

</div>

app/views/posts/edit.html.erb
<div>
  <%= render "form", post: @post %>
</div>
<div class="my-10">
  <%= link_to "Cancel", @post %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>Write your new post (markdown supported)</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Cancel", dashboards_path %>
</div>

app/views/posts/show.html.erb
<div class="text-xl">
  <%= @post.title %>
</div>
<div class="my-5">
  <%= markdown(@post.body) %>
</div>
<% if @user && @post.user_id == @user.id %>
<div class="flex">
  <div class="inline flex m-5 items-center w-fit h-10 border-2 border-blue-500 p-2 bg-blue-50 rounded-md">
    <%= link_to "Edit", edit_post_path(@post) %>
  </div>
  <div class="inline m-5">
    <%= button_to "Delete", @post, method: :delete, class: "px-2 h-10 border-2 border-blue-500 bg-blue-50 rounded-md" %>
  </div>
</div>
<% end %>